package com.sabibiz.enums;

public enum MovementType {
    PURCHASE_RECEIPT,
    PURCHASE_RETURN,
    SALE,
    SALE_RETURN,
    STOCK_ADJUSTMENT_IN,
    STOCK_ADJUSTMENT_OUT,
    STOCK_TRANSFER_IN,
    STOCK_TRANSFER_OUT,
    OPENING_STOCK,
    DAMAGE_LOSS,
    EXPIRY_WRITE_OFF,
    INVENTORY_COUNT_ADJUSTMENT
}